name: spacity_wheels_viewer
description: This is a package created in the style of the spacity wheels viewer, with which you can pass video url and get spacity wheels view.
version: 1.0.0+3
homepage: https://github.com/patildarshan66/reels_viewer

environment:
  sdk: ">=3.0.0 <3.15.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  chewie: ^1.7.1
  card_swiper: ^3.0.1
  cached_network_image: 3.3.0
  intl: ^0.18.0
  video_player: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter: